db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  username: 'postgres'
  password: 'root'
  synchronize: false

jwt:
  secret: 'example@123'

mysqldb:
  host: 'localhost'
  type: 'mysql'
  port: 3306
  database: 'truthy'
  username: 'root'
  password: ''
  synchronize: false
